trigger: 
  branches:
    include:
      - main
  paths:
    include:
      - webapp

variables:
  - group: 'Mine variabler'

pool:
  name: 'Minecraft server'
  vmImage: 'ubuntu-latest'

stages: 
  - stage:
    displayName: Dotnet Restore
    jobs: 
      - job:
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'Restore'
            inputs: 
              command: 'restore'
              projects: 'src/webapp/**/*.csproj'
              feedsToUse: 'select'

          - task: DotNetCoreCLI@2
            displayName: 'Build & Publish'
            inputs: 
              command: 'publish'
              projects: 'src/webapp/**/*.csproj'
              publishWebProjects: false
              arguments: '-o $(Build.ArtifactStagingDirectory) --configuration Release'

          - task: PublishPipelineArtifact@1
            displayName: 'Publish to pipeline'
            inputs: 
              targetPath: '$(Build.ArtifactStagingDirectory)'
              artifact: $(appName)
              publishLocation: pipeline

  - template: deployWebApp.yml
    parameters:
      Environment: $(environment)
      AppName: $(appName)
      ServiceConnection: $(azureServiceConnection)

    

          
